//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbangiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIO_HANG
    {
        public int CartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> So_luong { get; set; }
        public Nullable<int> San_pham_trong_gio { get; set; }
        public Nullable<decimal> Tong_so_tien { get; set; }
    }
}
